begin;

CREATE TABLE IF NOT EXISTS public.planning_inject (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  machine text,
  itemcode text,
  product_name text,
  customer text,
  wo text,
  netweight numeric,
  quanperh numeric,
  quanperday numeric,
  color text,
  material text,
  package text,
  quanorder numeric,
  source_file text,
  imported_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS planning_inject_machine_idx ON public.planning_inject(machine);
CREATE INDEX IF NOT EXISTS planning_inject_wo_idx ON public.planning_inject(wo);

CREATE OR REPLACE FUNCTION public.replace_planning_inject(
  p_rows jsonb,
  p_source_file text
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  inserted_count integer;
BEGIN
  IF NOT public.is_admin() AND NOT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND is_active = true AND position = 'planning'
  ) THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;

  TRUNCATE TABLE public.planning_inject RESTART IDENTITY;

  INSERT INTO public.planning_inject (
    machine,itemcode,product_name,customer,wo,netweight,quanperh,quanperday,
    color,material,package,quanorder,source_file,imported_at
  )
  SELECT
    x.machine,x.itemcode,x.product_name,x.customer,x.wo,x.netweight,x.quanperh,x.quanperday,
    x.color,x.material,x.package,x.quanorder,p_source_file,now()
  FROM jsonb_to_recordset(p_rows) AS x(
    machine text,itemcode text,product_name text,customer text,wo text,
    netweight numeric,quanperh numeric,quanperday numeric,color text,
    material text,package text,quanorder numeric
  );

  GET DIAGNOSTICS inserted_count = ROW_COUNT;
  RETURN inserted_count;
END;
$$;

ALTER TABLE public.planning_inject ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS planning_inject_read ON public.planning_inject;
CREATE POLICY planning_inject_read ON public.planning_inject
FOR SELECT TO authenticated USING (true);

REVOKE ALL ON public.planning_inject FROM anon;
GRANT SELECT ON public.planning_inject TO authenticated;
GRANT EXECUTE ON FUNCTION public.replace_planning_inject(jsonb,text) TO authenticated;

commit;
