begin;

CREATE TABLE IF NOT EXISTS public.item_pallet_config (
  itemcode text PRIMARY KEY,
  quantity_per_pallet integer NOT NULL CHECK (quantity_per_pallet > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.pallet_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pallet_id text NOT NULL UNIQUE,
  itemcode text NOT NULL,
  product_name text,
  customer text,
  wo text NOT NULL,
  quanorder numeric,
  machine text,
  quantity integer NOT NULL CHECK (quantity > 0),
  status text NOT NULL DEFAULT 'production',
  created_by uuid REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS pallet_data_wo_idx ON public.pallet_data(wo);
CREATE INDEX IF NOT EXISTS pallet_data_machine_idx ON public.pallet_data(machine);
CREATE INDEX IF NOT EXISTS pallet_data_status_idx ON public.pallet_data(status);

DROP TRIGGER IF EXISTS item_pallet_config_set_updated_at ON public.item_pallet_config;
CREATE TRIGGER item_pallet_config_set_updated_at
BEFORE UPDATE ON public.item_pallet_config
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS pallet_data_set_updated_at ON public.pallet_data;
CREATE TRIGGER pallet_data_set_updated_at
BEFORE UPDATE ON public.pallet_data
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.create_pallet_record(
  p_itemcode text,
  p_product_name text,
  p_customer text,
  p_wo text,
  p_quanorder numeric,
  p_machine text,
  p_quantity integer
)
RETURNS public.pallet_data
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  next_number integer;
  new_pallet_id text;
  new_row public.pallet_data;
BEGIN
  IF NOT public.is_admin() AND NOT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND is_active = true AND position = 'pallet'
  ) THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;

  IF coalesce(trim(p_wo), '') = '' THEN RAISE EXCEPTION 'WO is required'; END IF;
  IF coalesce(trim(p_itemcode), '') = '' THEN RAISE EXCEPTION 'Itemcode is required'; END IF;
  IF p_quantity IS NULL OR p_quantity <= 0 THEN RAISE EXCEPTION 'Quantity must be greater than 0'; END IF;

  PERFORM pg_advisory_xact_lock(hashtext(p_wo));

  SELECT coalesce(max((regexp_match(pallet_id, '-([0-9]+)$'))[1]::integer), 0) + 1
  INTO next_number
  FROM public.pallet_data
  WHERE wo = p_wo;

  new_pallet_id := p_wo || '-' || lpad(next_number::text, 3, '0');

  INSERT INTO public.pallet_data (
    pallet_id,itemcode,product_name,customer,wo,quanorder,machine,quantity,status,created_by
  ) VALUES (
    new_pallet_id,p_itemcode,p_product_name,p_customer,p_wo,p_quanorder,p_machine,p_quantity,'production',auth.uid()
  ) RETURNING * INTO new_row;

  RETURN new_row;
END;
$$;

ALTER TABLE public.item_pallet_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pallet_data ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS item_pallet_config_read ON public.item_pallet_config;
CREATE POLICY item_pallet_config_read ON public.item_pallet_config
FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS pallet_data_read ON public.pallet_data;
CREATE POLICY pallet_data_read ON public.pallet_data
FOR SELECT TO authenticated USING (true);

REVOKE ALL ON public.item_pallet_config FROM anon;
REVOKE ALL ON public.pallet_data FROM anon;
GRANT SELECT ON public.item_pallet_config TO authenticated;
GRANT SELECT ON public.pallet_data TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_pallet_record(text,text,text,text,numeric,text,integer) TO authenticated;

commit;
