begin;

alter table public.pallet_data
  add column if not exists wh_receipt text;

create table if not exists public.wh_receipt (
  id bigint generated by default as identity primary key,
  receipt_id text not null unique,
  receipt_date date not null default current_date,
  total_pallet integer not null check (total_pallet > 0),
  total_quantity bigint not null check (total_quantity > 0),
  user_id uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists pallet_data_wh_receipt_idx on public.pallet_data(wh_receipt);
create index if not exists wh_receipt_date_idx on public.wh_receipt(receipt_date desc);

alter table public.wh_receipt enable row level security;
drop policy if exists wh_receipt_read on public.wh_receipt;
create policy wh_receipt_read on public.wh_receipt
for select to authenticated using (true);

revoke all on public.wh_receipt from anon;
grant select on public.wh_receipt to authenticated;

create or replace function public.cancel_processing_pallets(p_pallet_ids text[])
returns setof public.pallet_data
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() and not exists (
    select 1 from public.profiles
    where id = auth.uid() and is_active = true and position = 'warehouse'
  ) then raise exception 'Not authorized'; end if;

  if coalesce(array_length(p_pallet_ids, 1), 0) = 0 then
    raise exception 'NO_PALLETS';
  end if;

  if exists (
    select 1
    from unnest(p_pallet_ids) as x(pallet_id)
    left join public.pallet_data p
      on p.pallet_id = x.pallet_id and p.effect_to is null
    where p.pallet_id is null or p.status <> 'processingWH'
  ) then raise exception 'PALLET_STATUS_CHANGED'; end if;

  return query
  update public.pallet_data
  set status = 'production', wh_receipt = null
  where pallet_id = any(p_pallet_ids)
    and effect_to is null
    and status = 'processingWH'
  returning *;
end;
$$;

create or replace function public.create_warehouse_receipt(p_pallet_ids text[])
returns table (
  receipt_id text,
  receipt_date date,
  total_pallet integer,
  total_quantity bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_date date := current_date;
  v_order integer;
  v_receipt_id text;
  v_total_pallet integer;
  v_total_quantity bigint;
begin
  if not public.is_admin() and not exists (
    select 1 from public.profiles
    where id = auth.uid() and is_active = true and position = 'warehouse'
  ) then raise exception 'Not authorized'; end if;

  if coalesce(array_length(p_pallet_ids, 1), 0) = 0 then
    raise exception 'NO_PALLETS';
  end if;

  perform pg_advisory_xact_lock(hashtext('WH_RECEIPT_' || to_char(v_date, 'YYYYMMDD')));

  if exists (
    select 1
    from unnest(p_pallet_ids) as x(pallet_id)
    left join public.pallet_data p
      on p.pallet_id = x.pallet_id and p.effect_to is null
    where p.pallet_id is null or p.status <> 'processingWH'
  ) then raise exception 'PALLET_STATUS_CHANGED'; end if;

  select count(*)::integer, coalesce(sum(quantity), 0)::bigint
    into v_total_pallet, v_total_quantity
  from public.pallet_data
  where pallet_id = any(p_pallet_ids)
    and effect_to is null
    and status = 'processingWH';

  select coalesce(max((regexp_match(w.receipt_id, '-([0-9]+)$'))[1]::integer), 0) + 1
    into v_order
  from public.wh_receipt w
  where w.receipt_date = v_date;

  v_receipt_id := 'WH-' || to_char(v_date, 'DDMMYY') || '-' || lpad(v_order::text, 3, '0');

  insert into public.wh_receipt(receipt_id, receipt_date, total_pallet, total_quantity, user_id)
  values (v_receipt_id, v_date, v_total_pallet, v_total_quantity, auth.uid());

  update public.pallet_data
  set status = 'WHdone', wh_receipt = v_receipt_id
  where pallet_id = any(p_pallet_ids)
    and effect_to is null
    and status = 'processingWH';

  return query select v_receipt_id, v_date, v_total_pallet, v_total_quantity;
end;
$$;

-- Keep scanner functions limited to the active pallet version.
create or replace function public.scan_pallet_to_pending(p_pallet_id text)
returns public.pallet_data
language plpgsql
security definer
set search_path = public
as $$
declare v_row public.pallet_data;
begin
  if not public.is_admin() and not exists (
    select 1 from public.profiles where id = auth.uid() and is_active = true and position = 'scanner'
  ) then raise exception 'Not authorized'; end if;

  update public.pallet_data set status = 'pendingWH'
  where pallet_id = trim(p_pallet_id) and effect_to is null and status = 'production'
  returning * into v_row;
  if found then return v_row; end if;

  select * into v_row from public.pallet_data
  where pallet_id = trim(p_pallet_id) and effect_to is null;
  if not found then raise exception 'PALLET_NOT_FOUND'; end if;
  raise exception 'INVALID_STATUS:%', v_row.status;
end;
$$;

create or replace function public.confirm_pending_pallets(p_pallet_ids text[])
returns setof public.pallet_data
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() and not exists (
    select 1 from public.profiles where id = auth.uid() and is_active = true and position = 'scanner'
  ) then raise exception 'Not authorized'; end if;
  if coalesce(array_length(p_pallet_ids, 1), 0) = 0 then raise exception 'NO_PALLETS'; end if;
  if exists (
    select 1 from unnest(p_pallet_ids) x(pallet_id)
    left join public.pallet_data p on p.pallet_id = x.pallet_id and p.effect_to is null
    where p.pallet_id is null or p.status <> 'pendingWH'
  ) then raise exception 'PALLET_STATUS_CHANGED'; end if;
  return query update public.pallet_data set status = 'processingWH'
  where pallet_id = any(p_pallet_ids) and effect_to is null and status = 'pendingWH'
  returning *;
end;
$$;

grant execute on function public.cancel_processing_pallets(text[]) to authenticated;
grant execute on function public.create_warehouse_receipt(text[]) to authenticated;

commit;
