begin;

-- Pallet-level flags used by the current application logic.
alter table public.pallet_data
  add column if not exists has_been_edited boolean not null default false,
  add column if not exists edit_count integer not null default 0,
  add column if not exists has_been_return boolean not null default false,
  add column if not exists scanned_at timestamptz;

-- The old return fields are no longer used. Return details now live in
-- pallet_change_history as one event for each cancelled scan.
alter table public.pallet_data
  drop column if exists return_at,
  drop column if exists return_by,
  drop column if exists return_from,
  drop column if exists returned_at,
  drop column if exists returned_by,
  drop column if exists returned_from;

-- pallet_change_history is now dedicated to scan-return events.
-- Edit/delete lineage remains in pallet_data.old_data_refer.
drop table if exists public.pallet_change_history;

create table public.pallet_change_history (
  id bigint generated by default as identity primary key,
  pallet_data_id bigint not null references public.pallet_data(id),
  pallet_id text not null,
  change_type text not null default 'scan_return'
    check (change_type = 'scan_return'),
  scanned_by uuid references auth.users(id),
  scanned_at timestamptz not null,
  cancelled_by uuid not null references auth.users(id),
  cancelled_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index pallet_change_history_pallet_data_id_idx
  on public.pallet_change_history(pallet_data_id);

create index pallet_change_history_pallet_id_idx
  on public.pallet_change_history(pallet_id);

create index pallet_change_history_cancelled_at_idx
  on public.pallet_change_history(cancelled_at desc);

alter table public.pallet_change_history enable row level security;

drop policy if exists pallet_change_history_read on public.pallet_change_history;
create policy pallet_change_history_read
  on public.pallet_change_history
  for select to authenticated
  using (true);

revoke all on public.pallet_change_history from anon;
grant select on public.pallet_change_history to authenticated;

-- Recreate edit RPC so a new active version keeps the edit audit flags.
drop function if exists public.edit_pallet_quantity_tracked(text, integer, text);

create function public.edit_pallet_quantity_tracked(
  p_pallet_id text,
  p_quantity integer,
  p_reason text
)
returns public.pallet_data
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old public.pallet_data;
  v_new public.pallet_data;
  v_now timestamptz := now();
begin
  if not public.is_admin() and not exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and is_active = true
      and position = 'production'
  ) then
    raise exception 'Not authorized';
  end if;

  if p_quantity is null or p_quantity <= 0 then
    raise exception 'INVALID_QUANTITY';
  end if;

  if coalesce(trim(p_reason), '') = '' then
    raise exception 'REASON_REQUIRED';
  end if;

  select * into v_old
  from public.pallet_data
  where pallet_id = trim(p_pallet_id)
    and effect_to is null
  for update;

  if not found then raise exception 'PALLET_NOT_FOUND'; end if;
  if v_old.status <> 'production' then
    raise exception 'INVALID_STATUS:%', v_old.status;
  end if;

  update public.pallet_data
  set effect_to = v_now,
      updated_at = v_now
  where id = v_old.id;

  insert into public.pallet_data (
    pallet_id,
    itemcode,
    product_name,
    customer,
    wo,
    quanorder,
    machine,
    quantity,
    status,
    created_by,
    note,
    old_data_refer,
    has_been_edited,
    edit_count,
    has_been_return,
    created_at,
    updated_at
  ) values (
    v_old.pallet_id,
    v_old.itemcode,
    v_old.product_name,
    v_old.customer,
    v_old.wo,
    v_old.quanorder,
    v_old.machine,
    p_quantity,
    v_old.status,
    auth.uid(),
    'edit: ' || trim(p_reason),
    v_old.id,
    true,
    coalesce(v_old.edit_count, 0) + 1,
    coalesce(v_old.has_been_return, false),
    v_now,
    v_now
  )
  returning * into v_new;

  return v_new;
end;
$$;

-- Record the exact time and user when a pallet is scanned.
drop function if exists public.scan_pallet_to_pending(text);

create function public.scan_pallet_to_pending(p_pallet_id text)
returns public.pallet_data
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.pallet_data;
begin
  if not public.is_admin() and not exists (
    select 1 from public.profiles
    where id = auth.uid()
      and is_active = true
      and position = 'warehouse'
  ) then
    raise exception 'Not authorized';
  end if;

  update public.pallet_data
  set status = 'pendingWH',
      scanned_by = auth.uid(),
      scanned_at = now()
  where pallet_id = trim(p_pallet_id)
    and effect_to is null
    and status = 'production'
  returning * into v_row;

  if found then return v_row; end if;

  select * into v_row
  from public.pallet_data
  where pallet_id = trim(p_pallet_id)
    and effect_to is null;

  if not found then raise exception 'PALLET_NOT_FOUND'; end if;
  raise exception 'INVALID_STATUS:%', v_row.status;
end;
$$;

-- Cancelling a scan no longer writes return_at/return_by/return_from.
-- It marks the pallet and inserts one scan-return history event.
drop function if exists public.cancel_pending_pallet(text);

create function public.cancel_pending_pallet(p_pallet_id text)
returns public.pallet_data
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.pallet_data;
  v_cancelled_at timestamptz := now();
begin
  select * into v_row
  from public.pallet_data
  where pallet_id = trim(p_pallet_id)
    and effect_to is null
  for update;

  if not found then raise exception 'PALLET_NOT_FOUND'; end if;
  if v_row.status <> 'pendingWH' then
    raise exception 'INVALID_STATUS:%', v_row.status;
  end if;

  if not public.is_admin() and v_row.scanned_by is distinct from auth.uid() then
    raise exception 'NOT_SCAN_OWNER';
  end if;

  insert into public.pallet_change_history (
    pallet_data_id,
    pallet_id,
    change_type,
    scanned_by,
    scanned_at,
    cancelled_by,
    cancelled_at
  ) values (
    v_row.id,
    v_row.pallet_id,
    'scan_return',
    v_row.scanned_by,
    coalesce(v_row.scanned_at, v_row.updated_at, v_cancelled_at),
    auth.uid(),
    v_cancelled_at
  );

  update public.pallet_data
  set status = 'production',
      scanned_by = null,
      scanned_at = null,
      has_been_return = true,
      updated_at = v_cancelled_at
  where id = v_row.id
  returning * into v_row;

  return v_row;
end;
$$;

grant execute on function public.edit_pallet_quantity_tracked(text, integer, text) to authenticated;
grant execute on function public.scan_pallet_to_pending(text) to authenticated;
grant execute on function public.cancel_pending_pallet(text) to authenticated;

commit;
