-- Pallet traceability through WHdone.
-- Normal workflow milestones stay on pallet_data.
-- Only edit/delete actions are appended to pallet_change_history.

alter table public.pallet_data
  add column if not exists created_by uuid,
  add column if not exists scanned_at timestamptz,
  add column if not exists scanned_by uuid,
  add column if not exists scan_confirmed_at timestamptz,
  add column if not exists scan_confirmed_by uuid,
  add column if not exists warehouse_done_at timestamptz,
  add column if not exists warehouse_done_by uuid,
  add column if not exists returned_at timestamptz,
  add column if not exists returned_by uuid,
  add column if not exists return_from_status text,
  add column if not exists has_been_edited boolean not null default false,
  add column if not exists edit_count integer not null default 0,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by uuid;

alter table public.pallet_data
  drop constraint if exists pallet_data_return_from_status_check;

alter table public.pallet_data
  add constraint pallet_data_return_from_status_check
  check (return_from_status is null or return_from_status in ('pendingWH', 'processingWH'));

create table if not exists public.pallet_change_history (
  id bigint generated by default as identity primary key,
  pallet_id text not null,
  action text not null check (action in ('edit', 'delete')),
  changed_at timestamptz not null default now(),
  changed_by uuid not null,
  old_data jsonb not null,
  new_data jsonb,
  reason text not null check (length(btrim(reason)) > 0)
);

create index if not exists pallet_change_history_pallet_id_idx
  on public.pallet_change_history (pallet_id, changed_at desc);

create index if not exists pallet_change_history_changed_by_idx
  on public.pallet_change_history (changed_by, changed_at desc);

alter table public.pallet_change_history enable row level security;

revoke insert, update, delete on public.pallet_change_history from anon, authenticated;
grant select on public.pallet_change_history to authenticated;

drop policy if exists pallet_change_history_authenticated_select on public.pallet_change_history;
create policy pallet_change_history_authenticated_select
  on public.pallet_change_history
  for select
  to authenticated
  using (true);

create or replace function public.track_pallet_workflow_fields()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
begin
  if tg_op = 'INSERT' then
    new.created_at := coalesce(new.created_at, now());
    new.created_by := coalesce(new.created_by, v_actor);
    return new;
  end if;

  -- WHdone is final in the current application scope.
  if old.status = 'WHdone' and new is distinct from old then
    raise exception 'WHDONE_LOCKED';
  end if;

  if new.status is distinct from old.status then
    case
      when old.status = 'production' and new.status = 'pendingWH' then
        new.scanned_at := now();
        new.scanned_by := v_actor;

      when old.status = 'pendingWH' and new.status = 'processingWH' then
        new.scan_confirmed_at := now();
        new.scan_confirmed_by := v_actor;

      when old.status = 'processingWH' and new.status = 'WHdone' then
        new.warehouse_done_at := now();
        new.warehouse_done_by := v_actor;

      when old.status in ('pendingWH', 'processingWH') and new.status = 'production' then
        new.returned_at := now();
        new.returned_by := v_actor;
        new.return_from_status := old.status;

      else
        raise exception 'INVALID_PALLET_STATUS_TRANSITION:%->%', old.status, new.status;
    end case;
  end if;

  return new;
end;
$$;

drop trigger if exists pallet_workflow_traceability_trigger on public.pallet_data;
create trigger pallet_workflow_traceability_trigger
before insert or update on public.pallet_data
for each row
execute function public.track_pallet_workflow_fields();

create or replace function public.edit_pallet_quantity_tracked(
  p_pallet_id text,
  p_quantity integer,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_current public.pallet_data%rowtype;
  v_updated public.pallet_data%rowtype;
begin
  if v_actor is null then
    raise exception 'UNAUTHENTICATED';
  end if;
  if p_quantity is null or p_quantity <= 0 then
    raise exception 'INVALID_QUANTITY';
  end if;
  if nullif(btrim(p_reason), '') is null then
    raise exception 'REASON_REQUIRED';
  end if;

  select * into v_current
  from public.pallet_data
  where pallet_id = p_pallet_id
    and effect_to is null
  for update;

  if not found then
    raise exception 'PALLET_NOT_FOUND';
  end if;
  if v_current.status <> 'production' then
    raise exception 'INVALID_STATUS:%', v_current.status;
  end if;

  update public.pallet_data
  set quantity = p_quantity,
      has_been_edited = true,
      edit_count = coalesce(edit_count, 0) + 1,
      note = case
        when note is null or btrim(note) = '' then 'edit: ' || btrim(p_reason)
        else note || E'\nedit: ' || btrim(p_reason)
      end
  where pallet_id = p_pallet_id
    and effect_to is null
  returning * into v_updated;

  insert into public.pallet_change_history (
    pallet_id, action, changed_by, old_data, new_data, reason
  ) values (
    p_pallet_id,
    'edit',
    v_actor,
    to_jsonb(v_current),
    to_jsonb(v_updated),
    btrim(p_reason)
  );

  return to_jsonb(v_updated);
end;
$$;

create or replace function public.delete_pallet_record_tracked(
  p_pallet_id text,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_current public.pallet_data%rowtype;
  v_updated public.pallet_data%rowtype;
begin
  if v_actor is null then
    raise exception 'UNAUTHENTICATED';
  end if;
  if nullif(btrim(p_reason), '') is null then
    raise exception 'REASON_REQUIRED';
  end if;

  select * into v_current
  from public.pallet_data
  where pallet_id = p_pallet_id
    and effect_to is null
  for update;

  if not found then
    raise exception 'PALLET_NOT_FOUND';
  end if;
  if v_current.status <> 'production' then
    raise exception 'INVALID_STATUS:%', v_current.status;
  end if;

  update public.pallet_data
  set effect_to = now(),
      deleted_at = now(),
      deleted_by = v_actor,
      note = case
        when note is null or btrim(note) = '' then 'delete: ' || btrim(p_reason)
        else note || E'\ndelete: ' || btrim(p_reason)
      end
  where pallet_id = p_pallet_id
    and effect_to is null
  returning * into v_updated;

  insert into public.pallet_change_history (
    pallet_id, action, changed_by, old_data, new_data, reason
  ) values (
    p_pallet_id,
    'delete',
    v_actor,
    to_jsonb(v_current),
    to_jsonb(v_updated),
    btrim(p_reason)
  );

  return to_jsonb(v_updated);
end;
$$;

revoke all on function public.edit_pallet_quantity_tracked(text, integer, text) from public;
revoke all on function public.delete_pallet_record_tracked(text, text) from public;
grant execute on function public.edit_pallet_quantity_tracked(text, integer, text) to authenticated, service_role;
grant execute on function public.delete_pallet_record_tracked(text, text) to authenticated, service_role;
